local cargo_asset_set_ladung_provider = {}
--mdl Beispiel

--local cargo_asset_set_ladung_provider = require "cargo_asset_set_ladung_provider";
--function data()
--  return {
--    ....

--CargoSlots:
--{
--	models = cargo_asset_set_ladung_provider.getLadungList1(),
--	group = 17,
--	transf = { 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, -4.63, 0, 1.165, 1, },
--	randomId = 4,
--},


function cargo_asset_set_container_provider.getLadung_coil_klein()
    return {
	"asset/beladung_mw/coil/coil3_aluminium.mdl",
	"asset/beladung_mw/coil/coil3_aluminium2.mdl",
	"asset/beladung_mw/coil/coil3_gedeckt.mdl",
	"asset/beladung_mw/coil/coil3_gedeckt2.mdl",
	"asset/beladung_mw/coil/coil3_gedeckt3.mdl",
	"asset/beladung_mw/coil/coil3_gedeckt4.mdl",
	"asset/beladung_mw/coil/coil3_gedeckt5.mdl",
	"asset/beladung_mw/coil/coil3_gedeckt6.mdl",
	"asset/beladung_mw/coil/coil3_kupfer.mdl",
	"asset/beladung_mw/coil/coil3_kupfer2.mdl",
	"asset/beladung_mw/coil/coil3_kupfer3.mdl",
	"asset/beladung_mw/coil/coil3_stahl.mdl",
	"asset/beladung_mw/coil/coil3_stahl2.mdl",
	"asset/beladung_mw/coil/coil3_stahl3.mdl",
	"asset/beladung_mw/coil/coil3_stahl4.mdl",
	"asset/beladung_mw/coil/coil3_stahl5.mdl",
	"asset/beladung_mw/coil/coil3_stahl6.mdl",								
	"asset/beladung_mw/coil/coil4_aluminium.mdl",
	"asset/beladung_mw/coil/coil4_aluminium2.mdl",
	"asset/beladung_mw/coil/coil4_gedeckt.mdl",
	"asset/beladung_mw/coil/coil4_gedeckt2.mdl",
	"asset/beladung_mw/coil/coil4_gedeckt3.mdl",
	"asset/beladung_mw/coil/coil4_gedeckt4.mdl",
	"asset/beladung_mw/coil/coil4_gedeckt5.mdl",
	"asset/beladung_mw/coil/coil4_gedeckt6.mdl",
	"asset/beladung_mw/coil/coil4_kupfer.mdl",
	"asset/beladung_mw/coil/coil4_kupfer2.mdl",
	"asset/beladung_mw/coil/coil4_kupfer3.mdl",
	"asset/beladung_mw/coil/coil4_stahl.mdl",
	"asset/beladung_mw/coil/coil4_stahl2.mdl",
	"asset/beladung_mw/coil/coil4_stahl3.mdl",
	"asset/beladung_mw/coil/coil4_stahl4.mdl",
	"asset/beladung_mw/coil/coil4_stahl5.mdl",
	"asset/beladung_mw/coil/coil4_stahl6.mdl",								
	"asset/beladung_mw/coil/coil6_aluminium.mdl",
	"asset/beladung_mw/coil/coil6_aluminium2.mdl",
	"asset/beladung_mw/coil/coil6_gedeckt.mdl",
	"asset/beladung_mw/coil/coil6_gedeckt2.mdl",
	"asset/beladung_mw/coil/coil6_gedeckt3.mdl",
	"asset/beladung_mw/coil/coil6_gedeckt4.mdl",
	"asset/beladung_mw/coil/coil6_gedeckt5.mdl",
	"asset/beladung_mw/coil/coil6_gedeckt6.mdl",
	"asset/beladung_mw/coil/coil6_kupfer.mdl",
	"asset/beladung_mw/coil/coil6_kupfer2.mdl",
	"asset/beladung_mw/coil/coil6_kupfer3.mdl",
	"asset/beladung_mw/coil/coil6_stahl.mdl",
	"asset/beladung_mw/coil/coil6_stahl2.mdl",
	"asset/beladung_mw/coil/coil6_stahl3.mdl",
	"asset/beladung_mw/coil/coil6_stahl4.mdl",
	"asset/beladung_mw/coil/coil6_stahl5.mdl",
	"asset/beladung_mw/coil/coil6_stahl6.mdl",
    }
end
function cargo_asset_set_container_provider.getLadung_coil_klein2()
    return {
	"asset/beladung_mw/coil/coil2_aluminium.mdl",
	"asset/beladung_mw/coil/coil2_aluminium2.mdl",
	"asset/beladung_mw/coil/coil2_gedeckt.mdl",
	"asset/beladung_mw/coil/coil2_gedeckt2.mdl",
	"asset/beladung_mw/coil/coil2_gedeckt3.mdl",
	"asset/beladung_mw/coil/coil2_gedeckt4.mdl",
	"asset/beladung_mw/coil/coil2_gedeckt5.mdl",
	"asset/beladung_mw/coil/coil2_gedeckt6.mdl",
	"asset/beladung_mw/coil/coil2_kupfer.mdl",
	"asset/beladung_mw/coil/coil2_kupfer2.mdl",
	"asset/beladung_mw/coil/coil2_kupfer3.mdl",
	"asset/beladung_mw/coil/coil2_stahl.mdl",
	"asset/beladung_mw/coil/coil2_stahl2.mdl",
	"asset/beladung_mw/coil/coil2_stahl3.mdl",
	"asset/beladung_mw/coil/coil2_stahl4.mdl",
	"asset/beladung_mw/coil/coil2_stahl5.mdl",
	"asset/beladung_mw/coil/coil2_stahl6.mdl",								
	"asset/beladung_mw/coil/coil5_aluminium.mdl",
	"asset/beladung_mw/coil/coil5_aluminium2.mdl",
	"asset/beladung_mw/coil/coil5_gedeckt.mdl",
	"asset/beladung_mw/coil/coil5_gedeckt2.mdl",
	"asset/beladung_mw/coil/coil5_gedeckt3.mdl",
	"asset/beladung_mw/coil/coil5_gedeckt4.mdl",
	"asset/beladung_mw/coil/coil5_gedeckt5.mdl",
	"asset/beladung_mw/coil/coil5_gedeckt6.mdl",
	"asset/beladung_mw/coil/coil5_kupfer.mdl",
	"asset/beladung_mw/coil/coil5_kupfer2.mdl",
	"asset/beladung_mw/coil/coil5_kupfer3.mdl",
	"asset/beladung_mw/coil/coil5_stahl.mdl",
	"asset/beladung_mw/coil/coil5_stahl2.mdl",
	"asset/beladung_mw/coil/coil5_stahl3.mdl",
	"asset/beladung_mw/coil/coil5_stahl4.mdl",
	"asset/beladung_mw/coil/coil5_stahl5.mdl",
	"asset/beladung_mw/coil/coil5_stahl6.mdl",
	"asset/beladung_mw/coil/coil10_aluminium.mdl",
	"asset/beladung_mw/coil/coil10_aluminium2.mdl",
	"asset/beladung_mw/coil/coil10_gedeckt.mdl",
	"asset/beladung_mw/coil/coil10_gedeckt2.mdl",
	"asset/beladung_mw/coil/coil10_gedeckt3.mdl",
	"asset/beladung_mw/coil/coil10_gedeckt4.mdl",
	"asset/beladung_mw/coil/coil10_gedeckt5.mdl",
	"asset/beladung_mw/coil/coil10_gedeckt6.mdl",
	"asset/beladung_mw/coil/coil10_kupfer.mdl",
	"asset/beladung_mw/coil/coil10_kupfer2.mdl",
	"asset/beladung_mw/coil/coil10_kupfer3.mdl",
	"asset/beladung_mw/coil/coil10_stahl.mdl",
	"asset/beladung_mw/coil/coil10_stahl2.mdl",
	"asset/beladung_mw/coil/coil10_stahl3.mdl",
	"asset/beladung_mw/coil/coil10_stahl4.mdl",
	"asset/beladung_mw/coil/coil10_stahl5.mdl",
	"asset/beladung_mw/coil/coil10_stahl6.mdl",
    }
end
function cargo_asset_set_container_provider.getLadung_coil_mittel()
    return {
	"asset/beladung_mw/coil/coil7_aluminium.mdl",
	"asset/beladung_mw/coil/coil7_aluminium2.mdl",
	"asset/beladung_mw/coil/coil7_gedeckt.mdl",
	"asset/beladung_mw/coil/coil7_gedeckt2.mdl",
	"asset/beladung_mw/coil/coil7_gedeckt3.mdl",
	"asset/beladung_mw/coil/coil7_gedeckt4.mdl",
	"asset/beladung_mw/coil/coil7_gedeckt5.mdl",
	"asset/beladung_mw/coil/coil7_gedeckt6.mdl",
	"asset/beladung_mw/coil/coil7_kupfer.mdl",
	"asset/beladung_mw/coil/coil7_kupfer2.mdl",
	"asset/beladung_mw/coil/coil7_kupfer3.mdl",
	"asset/beladung_mw/coil/coil7_stahl.mdl",
	"asset/beladung_mw/coil/coil7_stahl2.mdl",
	"asset/beladung_mw/coil/coil7_stahl3.mdl",
	"asset/beladung_mw/coil/coil7_stahl4.mdl",
	"asset/beladung_mw/coil/coil7_stahl5.mdl",
	"asset/beladung_mw/coil/coil7_stahl6.mdl",								
	"asset/beladung_mw/coil/coil8_aluminium.mdl",
	"asset/beladung_mw/coil/coil8_aluminium2.mdl",
	"asset/beladung_mw/coil/coil8_gedeckt.mdl",
	"asset/beladung_mw/coil/coil8_gedeckt2.mdl",
	"asset/beladung_mw/coil/coil8_gedeckt3.mdl",
	"asset/beladung_mw/coil/coil8_gedeckt4.mdl",
	"asset/beladung_mw/coil/coil8_gedeckt5.mdl",
	"asset/beladung_mw/coil/coil8_gedeckt6.mdl",
	"asset/beladung_mw/coil/coil8_kupfer.mdl",
	"asset/beladung_mw/coil/coil8_kupfer2.mdl",
	"asset/beladung_mw/coil/coil8_kupfer3.mdl",
	"asset/beladung_mw/coil/coil8_stahl.mdl",
	"asset/beladung_mw/coil/coil8_stahl2.mdl",
	"asset/beladung_mw/coil/coil8_stahl3.mdl",
	"asset/beladung_mw/coil/coil8_stahl4.mdl",
	"asset/beladung_mw/coil/coil8_stahl5.mdl",
	"asset/beladung_mw/coil/coil8_stahl6.mdl",									
	"asset/beladung_mw/coil/coil9_aluminium.mdl",
	"asset/beladung_mw/coil/coil9_aluminium2.mdl",
	"asset/beladung_mw/coil/coil9_gedeckt.mdl",
	"asset/beladung_mw/coil/coil9_gedeckt2.mdl",
	"asset/beladung_mw/coil/coil9_gedeckt3.mdl",
	"asset/beladung_mw/coil/coil9_gedeckt4.mdl",
	"asset/beladung_mw/coil/coil9_gedeckt5.mdl",
	"asset/beladung_mw/coil/coil9_gedeckt6.mdl",
	"asset/beladung_mw/coil/coil9_kupfer.mdl",
	"asset/beladung_mw/coil/coil9_kupfer2.mdl",
	"asset/beladung_mw/coil/coil9_kupfer3.mdl",
	"asset/beladung_mw/coil/coil9_stahl.mdl",
	"asset/beladung_mw/coil/coil9_stahl2.mdl",
	"asset/beladung_mw/coil/coil9_stahl3.mdl",
	"asset/beladung_mw/coil/coil9_stahl4.mdl",
	"asset/beladung_mw/coil/coil9_stahl5.mdl",
	"asset/beladung_mw/coil/coil9_stahl6.mdl",
    }
end
function cargo_asset_set_container_provider.getLadung_coil_groß()
    return {
	"asset/beladung_mw/coil/coil_aluminium.mdl",
	"asset/beladung_mw/coil/coil_aluminium2.mdl",
	"asset/beladung_mw/coil/coil_gedeckt.mdl",
	"asset/beladung_mw/coil/coil_gedeckt2.mdl",
	"asset/beladung_mw/coil/coil_gedeckt3.mdl",
	"asset/beladung_mw/coil/coil_gedeckt4.mdl",
	"asset/beladung_mw/coil/coil_gedeckt5.mdl",
	"asset/beladung_mw/coil/coil_gedeckt6.mdl",
	"asset/beladung_mw/coil/coil_kupfer.mdl",
	"asset/beladung_mw/coil/coil_kupfer2.mdl",
	"asset/beladung_mw/coil/coil_kupfer3.mdl",
	"asset/beladung_mw/coil/coil_stahl.mdl",
	"asset/beladung_mw/coil/coil_stahl2.mdl",
	"asset/beladung_mw/coil/coil_stahl3.mdl",
	"asset/beladung_mw/coil/coil_stahl4.mdl",						
	"asset/beladung_mw/coil/coil_stahl5.mdl",
	"asset/beladung_mw/coil/coil_stahl6.mdl",								
	"asset/beladung_mw/coil/coil11_aluminium.mdl",
	"asset/beladung_mw/coil/coil11_aluminium2.mdl",
	"asset/beladung_mw/coil/coil11_gedeckt.mdl",
	"asset/beladung_mw/coil/coil11_gedeckt2.mdl",
	"asset/beladung_mw/coil/coil11_gedeckt3.mdl",
	"asset/beladung_mw/coil/coil11_gedeckt4.mdl",
	"asset/beladung_mw/coil/coil11_gedeckt5.mdl",
	"asset/beladung_mw/coil/coil11_gedeckt6.mdl",
	"asset/beladung_mw/coil/coil11_kupfer.mdl",
	"asset/beladung_mw/coil/coil11_kupfer2.mdl",
	"asset/beladung_mw/coil/coil11_kupfer3.mdl",
	"asset/beladung_mw/coil/coil11_stahl.mdl",
	"asset/beladung_mw/coil/coil11_stahl2.mdl",
	"asset/beladung_mw/coil/coil11_stahl3.mdl",
	"asset/beladung_mw/coil/coil11_stahl4.mdl",
	"asset/beladung_mw/coil/coil11_stahl5.mdl",
	"asset/beladung_mw/coil/coil11_stahl6.mdl",
    }
end
function cargo_asset_set_container_provider.getLadung_mb_mp()
    return {
	
	"asset/truck_mw/mb_mp/mb_mp.mdl",
	"asset/truck_mw/mb_mp/mb_mp2.mdl",
	"asset/truck_mw/mb_mp/mb_mp3.mdl",
	"asset/truck_mw/mb_mp/mb_mp4.mdl",
	"asset/truck_mw/mb_mp/mb_mp5.mdl",
	"asset/truck_mw/mb_mp/mb_mp6.mdl",
	"asset/truck_mw/mb_mp/mb_mp7.mdl",
	"asset/truck_mw/mb_mp/mb_mp8.mdl",
	"asset/truck_mw/mb_mp/mb_mp9.mdl",
	"asset/truck_mw/mb_mp/mb_mp10.mdl",
	"asset/truck_mw/mb_mp/mb_mp11.mdl",
	"asset/truck_mw/mb_mp/mb_mp12.mdl",
	"asset/truck_mw/mb_mp/mb_mp13.mdl",
	"asset/truck_mw/mb_mp/mb_mp14.mdl",
	"asset/truck_mw/mb_mp/mb_mp15.mdl",
	"asset/truck_mw/mb_mp/mb_mp16.mdl",
	"asset/truck_mw/mb_mp/mb_mp17.mdl",
	"asset/truck_mw/mb_mp/mb_mp18.mdl",
	"asset/truck_mw/mb_mp/mb_mp19.mdl",
	"asset/truck_mw/mb_mp/mb_mp20.mdl",
	"asset/truck_mw/mb_mp/mb_mp21.mdl",
	"asset/truck_mw/mb_mp/mb_mp22.mdl",
	"asset/truck_mw/mb_mp/mb_mp23.mdl",
    }
end
function cargo_asset_set_container_provider.getLadung_platzhalter()
    return {
	"asset/beladung_mw/coil/coil2_aluminium.mdl",
	"asset/beladung_mw/coil/coil2_aluminium2.mdl",
    }
end


return cargo_asset_set_ladung_provider;